### ISSUE TITLE
Question regarding the body params validation

### ISSUE THREAD

**Issue by hgarcia** [wonderlic/swagger-validation#12]
I'm not sure if I'm looking at this the wrong way.
But the body params validation tends to validate the whole body each time, instead of getting the value from the body by name.
Ex: I declare a param of type body with the name "firstName" and I send a "firstName" value in the body I will expect the validator to read the value from reg.body.firstName

All other validators, form, qs, headers seems to behave as I would expect.

Let me know if this is a bug or is the expected behaviour and I can send a pull request.

Thanks.

**Comment by wonderlic-chrisk** [comment]
The body does validate the whole thing as once and that is intended behavior.

I think what you are referring to is the replaceValues call that on all the others do something like:

`req.form[param.name] = helper.getValue(param, ret);`

whereas the body does:

`req.body = helper.getValue(param, ret);`

The reason it does is that while there can be multiple form, querystring, etc. values passed in, there can only be one body. As such, there really isn't a property to assign the value to.

That all being said, the body will still validate the full object or type passed into the body based off the model.

Let me know if I misunderstood what you were trying to say.

**Comment by hgarcia** [comment]
Ok, I see. So body is treated as a single object, so I should define a type (or model) to validate all at once.
Thanks.
